const cardData = [
  {
    image: "/protetor-raquete-1.webp",
    imageAlt: "racket-protector-1",
    description: "Racket Protector",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: true },
      { label: "L", available: false },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/calcao-desportivo-com-bolsos.webp",
    imageAlt: "sports-shorts-with-pockets",
    description: "Sports Shorts with Pockets",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: false },
    ],
  },
  {
    image: "/saia-calcao.webp",
    imageAlt: "skirt-shorts",
    description: "Skirt Shorts",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: false },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/tshirt-desportiva.webp",
    imageAlt: "sports-tshirt",
    description: "Sports T-shirt",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: true },
      { label: "L", available: false },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/tshirt-desportiva.webp",
    imageAlt: "sports-tshirt",
    description: "Sports T-shirt",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: false },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/protetor-raquete-1.webp",
    imageAlt: "racket-protector-1",
    description: "Racket Protector",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: false },
    ],
  },
  {
    image: "/calcao-desportivo-com-bolsos.webp",
    imageAlt: "sports-shorts-with-pockets",
    description: "Sports Shorts with Pockets",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: false },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/saia-calcao.webp",
    imageAlt: "skirt-shorts",
    description: "Skirt Shorts",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: false },
    ],
  },
  {
    image: "/saia-calcao.webp",
    imageAlt: "skirt-shorts",
    description: "Skirt Shorts",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: true },
      { label: "L", available: false },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/calcao-desportivo-com-bolsos.webp",
    imageAlt: "sports-shorts-with-pockets",
    description: "Sports Shorts with Pockets",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: false },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/tshirt-desportiva.webp",
    imageAlt: "sports-tshirt",
    description: "Sports T-shirt",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: false },
    ],
  },
  {
    image: "/protetor-raquete-1.webp",
    imageAlt: "racket-protector-1",
    description: "Racket Protector",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: true },
      { label: "L", available: false },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/calcao-desportivo-com-bolsos.webp",
    imageAlt: "sports-shorts-with-pockets",
    description: "Sports Shorts with Pockets",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/protetor-raquete-1.webp",
    imageAlt: "racket-protector-1",
    description: "Racket Protector",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: true },
      { label: "L", available: false },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/tshirt-desportiva.webp",
    imageAlt: "sports-tshirt",
    description: "Sports T-shirt",
    price: 25.0,
    sizes: [
      { label: "S", available: false },
      { label: "M", available: true },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
  {
    image: "/saia-calcao.webp",
    imageAlt: "skirt-shorts",
    description: "Skirt Shorts",
    price: 25.0,
    sizes: [
      { label: "S", available: true },
      { label: "M", available: false },
      { label: "L", available: true },
      { label: "XL", available: true },
    ],
  },
];

export default cardData;
